spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 55957572

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.myhexin.tokenverification.model